version: 2,
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    assignees:
      - "jackmatt2"
    labels:
      - "dependencies"